### ISSUE TITLE
Mobile menu_v1

### ISSUE THREAD

**Issue by canon193** [canon193/your-tech-partner#12]
Make the hamburger menu look better in mobile view.
![image](https://github.com/canon193/your-tech-partner/assets/75739534/9f04e22e-6aa4-46e6-81a6-429a6a967c3f)

**Comment by canon193** [comment]
Styling similar to https://banvien.com/case-studies/

**Comment by kuem2405** [comment]
This issue has been fixed on the PR: https://github.com/canon193/your-tech-partner/pull/21
![Screenshot 2023-09-27 at 21 32 43](https://github.com/canon193/your-tech-partner/assets/7057686/48a3876d-f78d-4cfe-b85f-d8e9fcf7231e)
