### ISSUE TITLE
Send form request_v1

### ISSUE THREAD

**Issue by canon193** [canon193/your-tech-partner#13]
After successfully sending the form. Popup a window show Thank you for your messages. We will be in touch.

![image](https://github.com/canon193/your-tech-partner/assets/75739534/6deeafc0-cd26-4d96-a491-5e7bf2effed7)

**Comment by kuem2405** [comment]
https://github.com/canon193/your-tech-partner/pull/22
This issue has been fixed on the PR above.
![Screenshot 2023-09-27 at 22 05 52](https://github.com/canon193/your-tech-partner/assets/7057686/965d198a-80b5-4e03-8073-34b6218cdf65)
