### ISSUE TITLE
Sitemap_v1

### ISSUE THREAD

**Issue by canon193** [canon193/your-tech-partner#14]
Prepare a script or module to generate sitemap file.

**Comment by kuem2405** [comment]
This issue has been fixed on the PR: https://github.com/canon193/your-tech-partner/pull/24
![Screenshot 2023-09-27 at 23 39 18](https://github.com/canon193/your-tech-partner/assets/7057686/3767dc59-7bd8-4e0c-b89a-2ff47cc4ce4f)
