### ISSUE TITLE
Privacy Policy_V1

### ISSUE THREAD

**Issue by canon193** [canon193/your-tech-partner#16]
Format this page: /privacy-policy

![image](https://github.com/canon193/your-tech-partner/assets/75739534/db0aa22c-146a-4356-a25a-55c71a0b2777)

**Comment by kuem2405** [comment]
This issue has been fixed on the PR: https://github.com/canon193/your-tech-partner/pull/23
![Uploading Screenshot 2023-09-27 at 22.55.28.png…]()
