### ISSUE TITLE
Menu bar_v1

### ISSUE THREAD

**Issue by canon193** [canon193/your-tech-partner#18]
![image](https://github.com/canon193/your-tech-partner/assets/75739534/978e8bf0-4ea8-42d3-a5d5-54658e6c7024)

**Comment by kuem2405** [comment]
This issue has fixed
![Screenshot 2023-09-27 at 21 32 57](https://github.com/canon193/your-tech-partner/assets/7057686/b2a7a063-e8f6-4d30-bd97-4618fe9edfe3)
