### ISSUE TITLE
FAQ page

### ISSUE THREAD

**Issue by canon193** [canon193/your-tech-partner#19]
Make FAQ page and put in on top of menu, on the left side of About

**Comment by kuem2405** [comment]
It has been fixed on this PR: https://github.com/canon193/your-tech-partner/pull/21
![Screenshot 2023-09-28 at 21 40 15](https://github.com/canon193/your-tech-partner/assets/7057686/76bcb2f3-c59b-43c4-916f-8419c37bcb2b)
