### ISSUE TITLE
Ver2 service page

### ISSUE THREAD

**Issue by canon193** [canon193/your-tech-partner#25]
Make this box bigger
![image](https://github.com/canon193/your-tech-partner/assets/75739534/ec47f92d-6b72-4268-9c75-16ed7221af6f)

Align these sections.
![image](https://github.com/canon193/your-tech-partner/assets/75739534/7652068a-3da8-451e-9acc-463966f60c7c)

**Comment by kuem2405** [comment]
This issue has been fixed on this PR: https://github.com/canon193/your-tech-partner/pull/28
![Screenshot 2023-10-05 at 21 25 38](https://github.com/canon193/your-tech-partner/assets/7057686/52d579ba-c908-466c-b0d9-7b546c7d49f0)
