### ISSUE TITLE
Ver2 automation solutions

### ISSUE THREAD

**Issue by canon193** [canon193/your-tech-partner#26]
Make this page look better with the correct image resolution, heading for each section and create some unordered list.
http://localhost:3000/service/automation-solutions

**Comment by kuem2405** [comment]
This issue has been fixed on this PR: https://github.com/canon193/your-tech-partner/pull/28
![Screenshot 2023-10-05 at 21 27 59](https://github.com/canon193/your-tech-partner/assets/7057686/0ff56b6d-51ea-4a4d-9c7d-dc39fe3ebdcb)
